/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElAside: typeof import('element-plus/es')['ElAside']
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPageHeader: typeof import('element-plus/es')['ElPageHeader']
    ElResult: typeof import('element-plus/es')['ElResult']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    LayoutBase: typeof import('./../src/layouts/layout-base/index.vue')['default']
    LayoutBaseHeader: typeof import('./../src/layouts/layout-base/layout-base-header.vue')['default']
    LayoutFooter: typeof import('./../src/layouts/components/layout-footer.vue')['default']
    LayoutHeader: typeof import('./../src/layouts/layout-base/layout-header.vue')['default']
    LayoutLogo: typeof import('./../src/layouts/components/layout-logo.vue')['default']
    LayoutMain: typeof import('./../src/layouts/components/layout-main.vue')['default']
    LayoutMenu: typeof import('./../src/layouts/components/layout-menu.vue')['default']
    LayoutMenuCollapse: typeof import('./../src/layouts/components/layout-menu-collapse.vue')['default']
    LayoutMenus: typeof import('./../src/layouts/components/layout-menus.vue')['default']
    Layouts: typeof import('./../src/layouts/index.vue')['default']
    LayoutTab: typeof import('./../src/layouts/components/layout-tab.vue')['default']
    LayoutTag: typeof import('./../src/layouts/components/layout-tag.vue')['default']
    LayoutTop: typeof import('./../src/layouts/layout-top/index.vue')['default']
    LayoutTopHeader: typeof import('./../src/layouts/layout-top/layout-top-header.vue')['default']
    LayoutTopLogo: typeof import('./../src/layouts/layout-top/layout-top-logo.vue')['default']
    LayoutUser: typeof import('./../src/layouts/components/layout-user.vue')['default']
    MenuList: typeof import('./../src/layouts/components/menu-list.vue')['default']
    PlusTable: typeof import('plus-pro-components/es')['PlusTable']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
